[build]
  publish = "dist"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "16"
  NPM_VERSION = "8"
  YARN_ENABLED = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
